/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package de.appwerft.spinkit;

import org.appcelerator.kroll.KrollDict;

import android.graphics.Color;

//import org.appcelerator.kroll.KrollProxy;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.titanium.proxy.TiViewProxy;
import org.appcelerator.titanium.view.TiUIView;


import android.app.Activity;



// This proxy can be created by calling Spin.createExample({message: "hello world"})
@Kroll.proxy(creatableInModule = SpinKitModule.class)
public class SpinKitViewProxy extends TiViewProxy {
	// Standard Debugging variables
	public int spinnerType = 0 ;
	public int spinnerColor = Color.parseColor("#ffffff");
	public SpinnerView mView; 

	// Constructor
	public SpinKitViewProxy() {
		super();
	}

	@Override
	public TiUIView createView(Activity activity) {
		mView = new SpinnerView(this);
		mView.getLayoutParams().autoFillsHeight = true;
		mView.getLayoutParams().autoFillsWidth = true;
		mView.addSpinner(spinnerType,spinnerColor);
		return mView;
	}

	@Override
	public void handleCreationDict(KrollDict options) {
		super.handleCreationDict(options);
		if (options.containsKey("type")) {
			spinnerType = options.getInt("type");
		}
		if (options.containsKey("color")) {
			spinnerColor = Color.parseColor(options.getString("color"));
		}
	}
}